config/routes.rb
Rails.application.routes.draw do
  resources :movements
  root 'movements#index'

end

app/models/budget.rb
class Budget
  attr_accessor :total_balance, :movements, :total_incomes, :total_expenses
  
  def initialize
    @total_balance=0
    @total_incomes=0
    @total_expenses=0
    @movements=[]
  end
  
  def calculate_budget(movements)
   movements.each do |m| 
     if m.mov_class == "I"
       @total_balance += m.amount
       @total_incomes += m.amount
     else
       @total_balance -= m.amount
       @total_expenses += m.amount
     end
   end
 end
    
end

app/models/movement.rb
class Movement < ActiveRecord::Base
  scope :search, ->(data) {
    mov_class= data[:mov_class] if data[:mov_class].present?
    date1= data[:date1] if data[:date1].present?
    date2= data[:date2] if data[:date2].present?
    description= "%#{data[:description]}%" if data[:description].present?
    entity= data[:entity] if data[:entity].present?
    where("(mov_class = :mov_class OR :mov_class IS NULL)", mov_class: mov_class)
    .where("(entity = :entity OR :entity IS NULL)", entity: entity)
      .where("(description LIKE :description OR :description IS NULL)", description: description)
      .where("(date >= :date1 OR :date1 is NULL)", date1: date1)
        .where("(date <= :date2 OR :date2 is NULL)", date2: date2)

  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :set_movement, only: [:show, :edit, :update, :destroy]

  # GET /movements
  # GET /movements.json
  def index
    @movements = Movement.search(params).order("date desc")
    @budget=Budget.new
    @budget.calculate_budget(@movements)
  end

  # GET /movements/1
  # GET /movements/1.json
  def show
  end

  # GET /movements/new
  def new
    @movement = Movement.new
  end

  # GET /movements/1/edit
  def edit
  end

  # POST /movements
  # POST /movements.json
  def create
    @movement = Movement.new(movement_params)

    respond_to do |format|
      if @movement.save
        format.html { redirect_to @movement, notice: 'Movement was successfully created.' }
        format.json { render :show, status: :created, location: @movement }
      else
        format.html { render :new }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movements/1
  # PATCH/PUT /movements/1.json
  def update
    respond_to do |format|
      if @movement.update(movement_params)
        format.html { redirect_to @movement, notice: 'Movement was successfully updated.' }
        format.json { render :show, status: :ok, location: @movement }
      else
        format.html { render :edit }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1
  # DELETE /movements/1.json
  def destroy
    @movement.destroy
    respond_to do |format|
      format.html { redirect_to movements_url, notice: 'Movement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement
      @movement = Movement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movement_params
      params.require(:movement).permit(:entity, :mov_class, :date, :description, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Money</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'movements', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-106660987-1', 'auto');
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->
</head>
<body>
	


<%= yield %>

</body>
</html>

app/views/movements/_form.html.erb
<%= form_for(@movement) do |f| %>
  <% if @movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
      <% @movement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :entity %><br>
	<%= f.select :entity, options_for_select([["Personal", "PER"], ["Tecnología", "TYC"], ["Steico", "SCO"], ["Systek", "SYS"], ["Inktec","INK"], ["Sincor", "SNR"]], selected: @movement.entity) %>  

  <div class="field">
    <%= f.label :mov_class %><br>
	<%= f.select :mov_class, options_for_select([["Egreso", "E"], ["Ingreso", "I"]], selected: @movement.mov_class) %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select(:date,:start_year => 2015,:order => [:day, :month, :year]) %>
  </div>
    
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movements/edit.html.erb
<h1>Editing Movement</h1>

<%= render 'form' %>

<%= link_to 'Show', @movement %> |
<%= link_to 'Back', movements_path %>

app/views/movements/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
	<h3>Listing Movements <%= link_to 'New', new_movement_path, class: "btn btn-primary btn-xs " %> </h3>
	
	<%= form_tag(movements_path, method: "get") do %>
	  <%= label_tag(:q, "Class:") %>
	  <%= select_tag(:mov_class, options_for_select([["Egreso", "E"], ["Ingreso", "I"]], selected: params[:mov_class]), include_blank: "All") %> 
	  <br>
	  <%= label_tag(:q, "Entity:") %>
	  <%= select_tag(:entity, options_for_select([["Personal", "PER"], ["Tecnología", "TYC"], ["Steico", "SCO"], ["Systek", "SYS"], ["Inktec","INK"], ["Sincor", "SNR"]], selected: params[:entity]), include_blank: "All") %> 
	  <br>
	  <%= label_tag(:q, "Fr:") %>
	  <%= date_field_tag :date1, params[:date1], :order => [:day, :month, :year]%>
	  <br>
	  <%= label_tag(:q, "To:") %>
	  <%= date_field_tag :date2, params[:date2], :order => [:day, :month, :year]%> 
	  <br>
	  <%= label_tag(:q, "Descrip:") %>
	  <%= text_field_tag(:description, params[:description]) %>
	  <br>  
	  <%= submit_tag("Search") %>
	  <%= link_to "Clear", movements_path%>
	<% end %>
	<br>

	<table>
		<tbody>
			<tr>
				<td> I: </td>
				<td align="right"> <%= number_to_currency(@budget.total_incomes, unit:"") %>  </td>
			</tr>
			<tr>
				<td> E: </td>
				<td align="right"> <%= number_to_currency(@budget.total_expenses, unit:"") %>  </td>
			</tr>
			<tr>
				<td> B: </td>
				<td align="right"> <%= number_to_currency(@budget.total_balance, unit:"") %>  </td>
			</tr>
		</tbody>
	</table>
	<br>
	<div class="table">          

		<table id="MovementList" class="table-striped">
		  <thead>
		    <tr>
		      <th>C</th>
		      <th>Date</th>
		      <th>Description</th>
		      <th>Amount</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @movements.each do |movement| %>
		      <tr>
		        <td><%= movement.mov_class %></td>
		        <td><%= movement.date.strftime("%d/%m") %></td>
		        <td><%= movement.description %></td>
		        <td align="right"><%= number_with_precision(movement.amount, presicion: 2, delimiter: ",") %></td>
		        <td><%= link_to 'Shw', movement %></td>
		        <td><%= link_to 'Ed', edit_movement_path(movement) %></td>
		        <td><%= link_to 'Dtr', movement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		      </tr>
		    <% end %>

		  </tbody>
		</table>
	</div>
</div>

app/views/movements/new.html.erb
<h1>New Movement</h1>

<%= render 'form' %>

<%= link_to 'Back', movements_path %>

app/views/movements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entity:</strong>
  <%= @movement.entity %>
</p>

<p>
  <strong>Class:</strong>
  <%= @movement.mov_class %>
</p>

<p>
  <strong>Date:</strong>
  <%= @movement.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movement.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= number_with_precision(@movement.amount, presicion: 2, delimiter: ",") %>
</p>

<%= link_to 'New Movement', new_movement_path %> |
<%= link_to 'Edit', edit_movement_path(@movement) %> |
<%= link_to 'Back', movements_path %>